import SidebarMenu from '@/components/Dashboard/SideBarMenu';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen">
          <SidebarMenu />
          <div className=" flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
